spring:
    datasource:
        url: jdbc:mysql://localhost:3306/DB
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    data:
        rest:
            base-path: /api
            default-page-size: 10
            max-page-size: 10
    jpa:
        hibernate:
            ddl-auto: create
    h2:
        console:
            enabled: true
        path: /console
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 978253666245-k40sieaik0cos3h4v1sooquc6pmku3im.apps.googleusercontent.com
                        client-secret: J_kn0wZSg3r6Kk-XQtc8m0lU
                    facebook:
                        client-id: 252280255718316
                        client-secret: 70aa1f9ef6102b26a93d0f68b8245743
custom:
    oauth2:
        kakao:
            client-id: c9536c8d0df4839cbe035ab9d4f2a485
server:
    port: 8081